### ISSUE TITLE
Error when using keyword arguments

### ISSUE THREAD

**Issue by jsalik** [dig386/node-marshal#1]
When using keyword arguments like:
`def foo(bar: 'default')`

there's error:
`/gems/node-marshal-0.2.1/lib/node-marshal.rb:55:in `to_bin': Cannot interpret node 68 (NODE_KW_ARG) (ArgumentError)`

**Comment by alvoskov** [comment]
Thank you for the report. And what is the version of Ruby (ruby --version command output)?

**Comment by jsalik** [comment]
ruby 2.2.4p230 (2015-12-16 revision 53155) [armv7l-linux-eabihf]

**Comment by alvoskov** [comment]
I've found a reason of the problem (NODE_KW_ARG is just not implemented) and working at a new version that will include the fix.

**Comment by alvoskov** [comment]
@jsalik I,'ve released a new version of the gem that should resolve your problem. Please try it.

**Comment by jsalik** [comment]
@dig386 thanks! i'll try it and let you know

**Comment by jsalik** [comment]
Well this issue is fixed in new version but another there's another error. Please look at #2
